name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:



jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps: 
      - uses: actions/checkout@v3 
      - name: echo thinkgs
        env:
          # GIT_BRANCH: "$GITHUB_REF_NAME"
          # GIT_COMMIT_SHA: $GITHUB_SHA
          CCKEY: ${{ secrets.CCKEY }}
          TEMP: 123
        run: |
          GIT_BRANCH=$GITHUB_REF_NAME
          GIT_COMMIT_SHA=$GITHUB_SHA
          echo "GIT_BRANCH $GIT_BRANCH"
          echo "GIT_COMMIT_SHA $GIT_COMMIT_SHA"
          echo "CCKEY $CCKEY"

      - name: "Format report"
        run: |
          echo "GIT_BRANCH $GIT_BRANCH"
          echo "GIT_COMMIT_SHA $GIT_COMMIT_SHA"
          echo "CCKEY $CCKEY"