name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:



jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: $GITHUB_REF_NAME
      GIT_COMMIT_SHA: $GITHUB_SHA
      CCKEY: ${{ secrets.CCKEY }}
    strategy:
      matrix:
        node-version: [16.x]
    steps: 
      - uses: actions/checkout@v3 
      - name: echo thinkgs
        run: |
          echo "N. BRANCH $GITHUB_REF_NAME"
          echo "N. SHA $GITHUB_SHA"
          echo "BRANCH ${{ env.GIT_BRANCH }}"
          echo "SHA $GIT_COMMIT_SHA"
          echo "CCKEY $CCKEY"

      # - name: "Format report"
      #   run: |
      #     echo "$GIT_BRANCH, $GIT_COMMIT_SHA"
      #     chmod +x bin/cc-test-reporter
      #     bin/cc-test-reporter format-coverage -t lcov -o climate/codeclimate.total.json coverage/lcov.info
      #     ls climate
      #     bin/cc-test-reporter upload-coverage --debug -i climate/codeclimate.total.json -r ${{ env.CCKEY }}