name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CCKEY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run Coverage
        run: |
          yarn install
          CI=true yarn test --coverage

      - name: Set ENV for codeclimate (pull_request)
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "GIT_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF)" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Set ENV for codeclimate (push)
        run: |
          echo "GIT_BRANCH=$GITHUB_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: "Upload Report"
        if: github.actor != 'dependabot[bot]'
        run: |
          echo "VARIABLES $GIT_BRANCH , $GIT_COMMIT_SHA"
          bin/cc-test-reporter format-coverage --debug -t lcov -o climate/codeclimate.frontend.json coverage/lcov.info
          bin/cc-test-reporter sum-coverage climate/codeclimate.*.json -p 1 -o climate/codeclimate.total.json
          bin/cc-test-reporter upload-coverage -i climate/codeclimate.total.json

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
